Rails.application.routes.draw do
  get 'sessions/login'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'sessions/omniauth'
  get 'readers/new'
  get 'readers/create'
  get 'readers/edit'
  get 'readers/update'
  get 'readers/destroy'
  get 'readers/index'
  get 'readers/show'
  get 'books/new'
  get 'books/create'
  get 'books/edit'
  get 'books/update'
  get 'books/destroy'
  get 'books/index'
  get 'books/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/edit'
  get 'authors/update'
  get 'authors/destroy'
  get 'authors/index'
  get 'authors/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
